# SwiftLint Configuration for DogTV+
# Agent 1: Build System & Project Structure

# Included and excluded directories
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - DerivedData
  - .git
  - docs
  - fastlane

# Analyzer rules
analyzer_rules:
  - unused_import
  - capture_variable

# Disabled rules
disabled_rules:
  - todo
  - trailing_comma
  - multiple_closures_with_trailing_closure
  - file_length
  - type_body_length
  - identifier_name
  - force_try
  - line_length

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - computed_accessors_order
  - control_statement
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_capture_list
  - unused_declaration
  - unused_enumerated
  - unused_optional_binding
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

# Rule configurations
file_length:
  warning: 200
  error: 300

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

function_body_length:
  warning: 30
  error: 50

type_body_length:
  warning: 200
  error: 300

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 3
    error: 5

identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - url
    - UUID
    - uuid
    - x
    - y
    - z
    - r
    - g
    - b
    - a

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  # Ensure proper import organization
  import_organization:
    name: "Import Organization"
    regex: "^import\\s+[A-Z]"
    message: "Imports should be organized: Foundation first, then system frameworks, then third-party"
    severity: warning

  # Ensure proper MARK usage
  mark_usage:
    name: "MARK Usage"
    regex: "^\\s*// MARK: -"
    message: "Use proper MARK format: // MARK: - Section Name"
    severity: warning

  # Ensure proper availability attributes
  availability_attributes:
    name: "Availability Attributes"
    regex: "@available\\(.*\\)"
    message: "Use proper availability attributes for platform-specific code"
    severity: warning

# Reporter
reporter: "xcode"

# Strict mode
strict: false

# Warnings as errors
warnings_as_errors: false # Explicitly set to false to prevent warnings from failing the build