name: Swift Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Build and Test
      run: |
        xcodebuild clean build test -scheme DogTV+ -destination 'platform=tvOS Simulator,name=Apple TV' \
        -enableCodeCoverage YES 