default_platform(:tvos)

platform :tvos do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "DogTV+")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Release a new version to the App Store"
  lane :release do
    capture_screenshots
    build_app(scheme: "DogTV+")
    upload_to_app_store
  end
end 