# Development Quality Configuration
# SwiftLint configuration for DogTV+ project

# Disable/enable rules
disabled_rules:
  - trailing_whitespace # Allow trailing whitespace for formatting flexibility
  - function_body_length # Allow longer functions for complex UI/rendering code
  
enabled_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Custom rule configuration
line_length:
  warning: 120
  error: 140
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

type_body_length:
  warning: 300
  error: 500

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# Paths configuration
included:
  - Sources
  - Tests

excluded:
  - .build
  - Carthage
  - DerivedData
  - .swiftpm
  - Package.swift

# Custom rules
custom_rules:
  # Require documentation for public APIs
  public_docs:
    name: "Public API Documentation"
    regex: '^[ ]*public[ ]+(?:class|struct|enum|protocol|func|var|let)(?!.*///).*$'
    message: "Public APIs should be documented with ///"
    severity: warning
    
  # Prefer modern async/await over completion handlers
  prefer_async_await:
    name: "Prefer async/await"
    regex: 'completion:\s*@escaping\s*\([^)]*\)\s*->\s*Void'
    message: "Consider using async/await instead of completion handlers"
    severity: warning
    
  # Enforce TODO/FIXME format
  todo_format:
    name: "TODO Format"
    regex: '(?:TODO|FIXME)(?!:)'
    message: "TODO and FIXME should be followed by a colon and description"
    severity: warning

# SwiftLint Reporter
reporter: "xcode"

# Severity configuration
warning_threshold: 50
error_threshold: 100
